---
- hosts: all
  tasks:

#############################################################################
#
#                         Install MongoDB 3.2.1
#
#############################################################################

  - name: -------------------------------------------Install MongoDB 3.2.1
    shell: echo '------------------------------------Install MongoDB 3.2.1'

  - name: install mongo apt key
    shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

  - name: add mongo source list
    shell: echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

  - name: apt-get update
    shell: apt-get update
    ignore_errors: yes

  - name: install mongo
    shell: apt-get install -y mongodb-org=3.2.1 mongodb-org-server=3.2.1 mongodb-org-shell=3.2.1 mongodb-org-mongos=3.2.1 mongodb-org-tools=3.2.1

  - name: restart mongo
    wait_for: port=27017 delay=5

  - name: configure mongo2.6 network interface
    copy: src=mongo/mongod.conf dest=/etc/mongod.conf 

  - name: restart mongo
    shell: /etc/init.d/mongod restart
